name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Post Checkout code
      uses: actions/checkout@v2

    - name: Post Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Clean workspace (remove DragSales.java if present)
      run: |
        echo "Cleaning workspace..."
        rm -f src/test/java/DragSales.java || true

    - name: Compile Java files
      run: |
        javac -cp "lib/*" -d out $(find . -name "*.java")

    - name: Run TestNG
      run: |
        java -cp "lib/*:out" org.testng.TestNG src/test/java/testng/testng.xml

