name: Java CI with TestNG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Post Checkout code
      uses: actions/checkout@v2

    - name: Post Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile Java files
      run: |
        mkdir -p out
        javac -cp "lib/*" -d out $(find src -name "*.java")

    - name: Run TestNG
      run: |
        java -cp "lib/*:out" org.testng.TestNG src/test/java/testng/testng.xml


